services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-lineage-demo
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
    volumes:
      - neo4j_data:/data
      - ./seed:/var/lib/neo4j/import

volumes:
  neo4j_data:
